export const STAGE_DEFS = Object.freeze({
  ember_keep: Object.freeze({
    id: 'ember_keep',
    name: 'EMBER KEEP',
    tagline: 'Bronze furnace ring',
    description: 'A straight-up castle furnace court: round floor, hot braziers, heavy walls, nowhere to hide from the edge.',
    startDistance: 5.0,
    bounds: Object.freeze({ type: 'circle', radius: 8.0 }),
    ui: Object.freeze({
      accent: '#dfa160',
      accentSoft: '#6a381d',
      panelTop: 'rgba(53, 24, 15, 0.94)',
      panelBottom: 'rgba(11, 10, 14, 0.98)',
      border: 'rgba(223, 161, 96, 0.42)',
      glow: 'rgba(255, 165, 87, 0.18)',
      muted: '#d8bf95',
      metrics: Object.freeze([
        Object.freeze({ label: 'Shape', value: 'Circle' }),
        Object.freeze({ label: 'Space', value: 'Even' }),
        Object.freeze({ label: 'Pressure', value: 'Measured' }),
        Object.freeze({ label: 'Open', value: '5.0m' }),
      ]),
    }),
    arena: Object.freeze({
      platformTop: 0x5b4a3c,
      platformSide: 0x352922,
      trim: 0xc18a4d,
      ring: 0xa56c3e,
      center: 0x7b4433,
      marker: 0xd49c5d,
      ground: 0x1b1310,
      detail: 0x2e1d19,
      roughness: 0.84,
      metalness: 0.08,
      decorKind: 'braziers',
      accentGlow: 0xff9a4a,
      motif: 'rings',
      outerInset: 0.1,
      ringOuterInset: 3.0,
      ringInnerInset: 3.7,
      centerInset: 6.9,
      markerInset: 0.55,
      perimeterOffset: 2.8,
    }),
    environment: Object.freeze({
      background: 0x120b0a,
      fogColor: 0x161012,
      fogDensity: 0.038,
      hemiSky: 0xffd6aa,
      hemiGround: 0x2b120d,
      hemiIntensity: 0.58,
      mainLightColor: 0xffe1bd,
      mainLightIntensity: 1.22,
      mainLightPosition: [5, 10, 4],
      rimLightColor: 0xff8d52,
      rimLightIntensity: 0.44,
      rimLightPosition: [-5, 4, -6],
      ambientColor: 0x2a1412,
      ambientIntensity: 0.34,
      particleColor: 0xffb36c,
      particleOpacity: 0.34,
      particleCount: 46,
      particleSize: 0.06,
      particleSpread: 22,
      particleHeight: 8.5,
      particleRiseSpeed: 0.14,
      particleDrift: 0.1,
      skyDiscColor: 0xffbf7c,
      skyDiscOpacity: 0.24,
      skyDiscSize: 5.8,
      skyDiscPosition: [-13, 7.5, -18],
      horizonColor: 0x29150f,
      horizonOpacity: 0.72,
      horizonHeight: 5.2,
      backdropKind: 'keep',
      backdropColor: 0x261410,
      backdropAccent: 0x8f4d29,
      backdropGlow: 0xff9d51,
    }),
  }),
  moon_garden: Object.freeze({
    id: 'moon_garden',
    name: 'MOON GARDEN',
    tagline: 'Wide octagonal moon court',
    description: 'A classic moon-viewing courtyard: octagonal stone, lantern rows, open diagonals, and a giant cold sky.',
    startDistance: 5.45,
    bounds: Object.freeze({ type: 'octagon', radius: 9.15 }),
    ui: Object.freeze({
      accent: '#9fcfff',
      accentSoft: '#243d5c',
      panelTop: 'rgba(20, 29, 45, 0.94)',
      panelBottom: 'rgba(7, 11, 18, 0.98)',
      border: 'rgba(159, 207, 255, 0.4)',
      glow: 'rgba(159, 207, 255, 0.16)',
      muted: '#cdddf6',
      metrics: Object.freeze([
        Object.freeze({ label: 'Shape', value: 'Octagon' }),
        Object.freeze({ label: 'Space', value: 'Wide' }),
        Object.freeze({ label: 'Pressure', value: 'Lateral' }),
        Object.freeze({ label: 'Open', value: '5.45m' }),
      ]),
    }),
    arena: Object.freeze({
      platformTop: 0x48505d,
      platformSide: 0x262b35,
      trim: 0xa6bdd4,
      ring: 0x6f89a4,
      center: 0x2c3948,
      marker: 0xd7e9ff,
      ground: 0x0b1118,
      detail: 0x1a2430,
      roughness: 0.8,
      metalness: 0.04,
      decorKind: 'lanterns',
      accentGlow: 0xa8d9ff,
      motif: 'facets',
      outerInset: 0.12,
      ringOuterInset: 2.6,
      ringInnerInset: 3.25,
      centerInset: 7.6,
      markerInset: 0.7,
      perimeterOffset: 3.0,
    }),
    environment: Object.freeze({
      background: 0x09111a,
      fogColor: 0x0f1821,
      fogDensity: 0.043,
      hemiSky: 0xaac4e8,
      hemiGround: 0x101116,
      hemiIntensity: 0.63,
      mainLightColor: 0xd7e7ff,
      mainLightIntensity: 1.1,
      mainLightPosition: [3, 11, 6],
      rimLightColor: 0x7eb8ff,
      rimLightIntensity: 0.5,
      rimLightPosition: [-6, 5, -8],
      ambientColor: 0x141a28,
      ambientIntensity: 0.38,
      particleColor: 0xcde5ff,
      particleOpacity: 0.24,
      particleCount: 52,
      particleSize: 0.055,
      particleSpread: 20,
      particleHeight: 9,
      particleRiseSpeed: 0.09,
      particleDrift: 0.08,
      skyDiscColor: 0xe2efff,
      skyDiscOpacity: 0.82,
      skyDiscSize: 6.4,
      skyDiscPosition: [-15, 10.5, -20],
      horizonColor: 0x0d1624,
      horizonOpacity: 0.68,
      horizonHeight: 5.6,
      backdropKind: 'garden',
      backdropColor: 0x131c28,
      backdropAccent: 0x5274a0,
      backdropGlow: 0xb9dcff,
    }),
  }),
  jade_sanctum: Object.freeze({
    id: 'jade_sanctum',
    name: 'JADE SANCTUM',
    tagline: 'Long elliptical sanctum',
    description: 'A temple-causeway stage: long lanes, jade accents, and strong left-right pressure like a ceremonial hall.',
    startDistance: 5.6,
    bounds: Object.freeze({ type: 'ellipse', radiusX: 9.6, radiusZ: 6.25 }),
    ui: Object.freeze({
      accent: '#73ddb4',
      accentSoft: '#1d5a46',
      panelTop: 'rgba(17, 33, 28, 0.94)',
      panelBottom: 'rgba(8, 14, 13, 0.98)',
      border: 'rgba(115, 221, 180, 0.42)',
      glow: 'rgba(115, 221, 180, 0.16)',
      muted: '#c8f0de',
      metrics: Object.freeze([
        Object.freeze({ label: 'Shape', value: 'Ellipse' }),
        Object.freeze({ label: 'Space', value: 'Long' }),
        Object.freeze({ label: 'Pressure', value: 'Lanes' }),
        Object.freeze({ label: 'Open', value: '5.6m' }),
      ]),
    }),
    arena: Object.freeze({
      platformTop: 0x435249,
      platformSide: 0x253129,
      trim: 0x7ad9b7,
      ring: 0x5e9e86,
      center: 0x31443d,
      marker: 0xbef1da,
      ground: 0x0d1712,
      detail: 0x1c2e26,
      roughness: 0.87,
      metalness: 0.03,
      decorKind: 'obelisks',
      accentGlow: 0x70dcb1,
      motif: 'aisle',
      outerInset: 0.12,
      ringOuterInset: 2.15,
      ringInnerInset: 2.9,
      centerInset: 5.0,
      markerInset: 0.72,
      perimeterOffset: 2.8,
    }),
    environment: Object.freeze({
      background: 0x0c1714,
      fogColor: 0x12211b,
      fogDensity: 0.04,
      hemiSky: 0x93d6c0,
      hemiGround: 0x0d120f,
      hemiIntensity: 0.56,
      mainLightColor: 0xd7ffe2,
      mainLightIntensity: 1.02,
      mainLightPosition: [4, 10, 3],
      rimLightColor: 0x4cd2a7,
      rimLightIntensity: 0.42,
      rimLightPosition: [-4, 5, -7],
      ambientColor: 0x10211b,
      ambientIntensity: 0.36,
      particleColor: 0xa5ffe2,
      particleOpacity: 0.22,
      particleCount: 48,
      particleSize: 0.05,
      particleSpread: 21,
      particleHeight: 8,
      particleRiseSpeed: 0.075,
      particleDrift: 0.07,
      skyDiscColor: 0x8cffe4,
      skyDiscOpacity: 0.26,
      skyDiscSize: 5.1,
      skyDiscPosition: [0, 9.2, -21],
      horizonColor: 0x0f1d18,
      horizonOpacity: 0.7,
      horizonHeight: 5.0,
      backdropKind: 'sanctum',
      backdropColor: 0x182923,
      backdropAccent: 0x5f9b87,
      backdropGlow: 0x70dcb1,
    }),
  }),
  ashen_shrine: Object.freeze({
    id: 'ashen_shrine',
    name: 'ASHEN SHRINE',
    tagline: 'Tight rounded square kill box',
    description: 'A shrine execution yard: cramped, squared-off, torch red, and hostile at the corners almost immediately.',
    startDistance: 4.75,
    bounds: Object.freeze({ type: 'roundedRect', halfWidth: 7.3, halfDepth: 5.95, cornerRadius: 1.45 }),
    ui: Object.freeze({
      accent: '#ff746a',
      accentSoft: '#612127',
      panelTop: 'rgba(36, 13, 17, 0.94)',
      panelBottom: 'rgba(10, 8, 13, 0.98)',
      border: 'rgba(255, 116, 106, 0.44)',
      glow: 'rgba(255, 116, 106, 0.18)',
      muted: '#f1c0bb',
      metrics: Object.freeze([
        Object.freeze({ label: 'Shape', value: 'Round Box' }),
        Object.freeze({ label: 'Space', value: 'Tight' }),
        Object.freeze({ label: 'Pressure', value: 'Brutal' }),
        Object.freeze({ label: 'Open', value: '4.75m' }),
      ]),
    }),
    arena: Object.freeze({
      platformTop: 0x2d2c32,
      platformSide: 0x151419,
      trim: 0xd14f4f,
      ring: 0x7d3131,
      center: 0x431d24,
      marker: 0xff9c91,
      ground: 0x09080c,
      detail: 0x1a0f15,
      roughness: 0.78,
      metalness: 0.09,
      decorKind: 'shrines',
      accentGlow: 0xff5f5f,
      motif: 'cross',
      outerInset: 0.12,
      ringOuterInset: 1.75,
      ringInnerInset: 2.4,
      centerInset: 4.7,
      markerInset: 0.6,
      perimeterOffset: 2.65,
    }),
    environment: Object.freeze({
      background: 0x09070c,
      fogColor: 0x130d14,
      fogDensity: 0.046,
      hemiSky: 0xc4a8c2,
      hemiGround: 0x150d0e,
      hemiIntensity: 0.5,
      mainLightColor: 0xffd7d2,
      mainLightIntensity: 1.08,
      mainLightPosition: [6, 10, 4],
      rimLightColor: 0xff6767,
      rimLightIntensity: 0.52,
      rimLightPosition: [-5, 5, -7],
      ambientColor: 0x170f18,
      ambientIntensity: 0.34,
      particleColor: 0xff8170,
      particleOpacity: 0.26,
      particleCount: 44,
      particleSize: 0.058,
      particleSpread: 23,
      particleHeight: 8.5,
      particleRiseSpeed: 0.11,
      particleDrift: 0.09,
      skyDiscColor: 0xff6a5a,
      skyDiscOpacity: 0.34,
      skyDiscSize: 5.4,
      skyDiscPosition: [14, 7.4, -18],
      horizonColor: 0x170d12,
      horizonOpacity: 0.76,
      horizonHeight: 5.3,
      backdropKind: 'shrine',
      backdropColor: 0x211015,
      backdropAccent: 0x7b2b31,
      backdropGlow: 0xff5f5f,
    }),
  }),
});

export const DEFAULT_STAGE = 'ember_keep';
export const STAGE_IDS = Object.freeze(Object.keys(STAGE_DEFS));

export function isValidStageId(stageId) {
  return Boolean(stageId && STAGE_DEFS[stageId]);
}

export function getStageDef(stageId = DEFAULT_STAGE) {
  return STAGE_DEFS[isValidStageId(stageId) ? stageId : DEFAULT_STAGE];
}
