export const STAGE_DEFS = Object.freeze({
  ember_keep: Object.freeze({
    id: 'ember_keep',
    name: 'EMBER KEEP',
    tagline: 'Bronze court under furnace light',
    description: 'A warm dueling ring framed by braziers, brass trim, and drifting embers.',
    arena: Object.freeze({
      platformTop: 0x5b4a3c,
      platformSide: 0x352922,
      trim: 0xc18a4d,
      ring: 0xa56c3e,
      center: 0x7b4433,
      marker: 0xd49c5d,
      ground: 0x1b1310,
      detail: 0x2e1d19,
      roughness: 0.84,
      metalness: 0.08,
      decorKind: 'braziers',
      accentGlow: 0xff9a4a,
    }),
    environment: Object.freeze({
      background: 0x120b0a,
      fogColor: 0x161012,
      fogDensity: 0.038,
      hemiSky: 0xffd6aa,
      hemiGround: 0x2b120d,
      hemiIntensity: 0.58,
      mainLightColor: 0xffe1bd,
      mainLightIntensity: 1.22,
      mainLightPosition: [5, 10, 4],
      rimLightColor: 0xff8d52,
      rimLightIntensity: 0.44,
      rimLightPosition: [-5, 4, -6],
      ambientColor: 0x2a1412,
      ambientIntensity: 0.34,
      particleColor: 0xffb36c,
      particleOpacity: 0.34,
      particleCount: 46,
      particleSize: 0.06,
      particleSpread: 22,
      particleHeight: 8.5,
      particleRiseSpeed: 0.14,
      particleDrift: 0.1,
    }),
  }),
  moon_garden: Object.freeze({
    id: 'moon_garden',
    name: 'MOON GARDEN',
    tagline: 'Cold stone and pale lantern mist',
    description: 'A silver-blue ring surrounded by lantern posts and drifting moonlit dust.',
    arena: Object.freeze({
      platformTop: 0x48505d,
      platformSide: 0x262b35,
      trim: 0xa6bdd4,
      ring: 0x6f89a4,
      center: 0x2c3948,
      marker: 0xd7e9ff,
      ground: 0x0b1118,
      detail: 0x1a2430,
      roughness: 0.8,
      metalness: 0.04,
      decorKind: 'lanterns',
      accentGlow: 0xa8d9ff,
    }),
    environment: Object.freeze({
      background: 0x09111a,
      fogColor: 0x0f1821,
      fogDensity: 0.043,
      hemiSky: 0xaac4e8,
      hemiGround: 0x101116,
      hemiIntensity: 0.63,
      mainLightColor: 0xd7e7ff,
      mainLightIntensity: 1.1,
      mainLightPosition: [3, 11, 6],
      rimLightColor: 0x7eb8ff,
      rimLightIntensity: 0.5,
      rimLightPosition: [-6, 5, -8],
      ambientColor: 0x141a28,
      ambientIntensity: 0.38,
      particleColor: 0xcde5ff,
      particleOpacity: 0.24,
      particleCount: 52,
      particleSize: 0.055,
      particleSpread: 20,
      particleHeight: 9,
      particleRiseSpeed: 0.09,
      particleDrift: 0.08,
    }),
  }),
  jade_sanctum: Object.freeze({
    id: 'jade_sanctum',
    name: 'JADE SANCTUM',
    tagline: 'Verdigris ruin above still earth',
    description: 'A weathered court of green stone, old idols, and soft motes in the air.',
    arena: Object.freeze({
      platformTop: 0x435249,
      platformSide: 0x253129,
      trim: 0x7ad9b7,
      ring: 0x5e9e86,
      center: 0x31443d,
      marker: 0xbef1da,
      ground: 0x0d1712,
      detail: 0x1c2e26,
      roughness: 0.87,
      metalness: 0.03,
      decorKind: 'obelisks',
      accentGlow: 0x70dcb1,
    }),
    environment: Object.freeze({
      background: 0x0c1714,
      fogColor: 0x12211b,
      fogDensity: 0.04,
      hemiSky: 0x93d6c0,
      hemiGround: 0x0d120f,
      hemiIntensity: 0.56,
      mainLightColor: 0xd7ffe2,
      mainLightIntensity: 1.02,
      mainLightPosition: [4, 10, 3],
      rimLightColor: 0x4cd2a7,
      rimLightIntensity: 0.42,
      rimLightPosition: [-4, 5, -7],
      ambientColor: 0x10211b,
      ambientIntensity: 0.36,
      particleColor: 0xa5ffe2,
      particleOpacity: 0.22,
      particleCount: 48,
      particleSize: 0.05,
      particleSpread: 21,
      particleHeight: 8,
      particleRiseSpeed: 0.075,
      particleDrift: 0.07,
    }),
  }),
  ashen_shrine: Object.freeze({
    id: 'ashen_shrine',
    name: 'ASHEN SHRINE',
    tagline: 'Obsidian ring beneath red smoke',
    description: 'A stark black shrine ringed by red monoliths and a slow storm of ash.',
    arena: Object.freeze({
      platformTop: 0x2d2c32,
      platformSide: 0x151419,
      trim: 0xd14f4f,
      ring: 0x7d3131,
      center: 0x431d24,
      marker: 0xff9c91,
      ground: 0x09080c,
      detail: 0x1a0f15,
      roughness: 0.78,
      metalness: 0.09,
      decorKind: 'shrines',
      accentGlow: 0xff5f5f,
    }),
    environment: Object.freeze({
      background: 0x09070c,
      fogColor: 0x130d14,
      fogDensity: 0.046,
      hemiSky: 0xc4a8c2,
      hemiGround: 0x150d0e,
      hemiIntensity: 0.5,
      mainLightColor: 0xffd7d2,
      mainLightIntensity: 1.08,
      mainLightPosition: [6, 10, 4],
      rimLightColor: 0xff6767,
      rimLightIntensity: 0.52,
      rimLightPosition: [-5, 5, -7],
      ambientColor: 0x170f18,
      ambientIntensity: 0.34,
      particleColor: 0xff8170,
      particleOpacity: 0.26,
      particleCount: 44,
      particleSize: 0.058,
      particleSpread: 23,
      particleHeight: 8.5,
      particleRiseSpeed: 0.11,
      particleDrift: 0.09,
    }),
  }),
});

export const DEFAULT_STAGE = 'ember_keep';
export const STAGE_IDS = Object.freeze(Object.keys(STAGE_DEFS));

export function isValidStageId(stageId) {
  return Boolean(stageId && STAGE_DEFS[stageId]);
}

export function getStageDef(stageId = DEFAULT_STAGE) {
  return STAGE_DEFS[isValidStageId(stageId) ? stageId : DEFAULT_STAGE];
}
