import { WeaponType } from '../core/Constants.js';
import { DEFAULT_WEAPON_TUNING } from '../combat/CombatTuning.js';

export const CHARACTER_DEFS = {
  spearman: {
    displayName: 'Spearman',
    glbPath: '/spearman.glb',
    weaponType: WeaponType.SPEAR,
    modelYOffset: -0.02,
    modelRotationX: -0.02,
    idleDuringStepCooldown: true,
    walkSpeedMult: 0.5,
    clipSpeedups: {
      walk: ['walk_forward', 'walk_backward'],
      strafe: ['strafe_left', 'strafe_right'],
      attack: ['attack_quick', 'attack_heavy', 'attack_thrust'],
      backstep: ['backstep'],
      knockback: ['clash_knockback', 'block_knockback'],
    },
      clipSpeedFactor: { walk: 1, strafe: 2, attack: 2, backstep: 3, knockback: 2 },
      clipSpeedOverrides: {
        walk_forward: 1.9,
        walk_backward: 2.1,
        strafe_left: 1.484375,
        strafe_right: 1.2109375,
        block_parry: 1.25,
        clash_knockback: 2.5,
        block_knockback: 2.5,
      },
      hipsLeanDeg: 4.5,
    swapIdle: { from: 'idle_alt', to: 'idle' },
    bakeWeapon: true,
    aiRanges: { engage: 3.5, close: 2.5 },
    attackStrength: 1.0,
    defenseStoutness: 0.95,
    bodySeparation: 1.6,
    weaponClashRadius: DEFAULT_WEAPON_TUNING[WeaponType.SPEAR].clashRadius,
    weaponHitRadius: DEFAULT_WEAPON_TUNING[WeaponType.SPEAR].hitRadius,
  },
  ronin: {
    displayName: 'Ronin',
    glbPath: '/ronin.glb',
    weaponType: WeaponType.KATANA,
    modelYOffset: -0.15,
    modelRotationX: -0.05,
    idleDuringStepCooldown: true,
    walkSpeedMult: 0.5,
    clipSpeedups: {
      walk: ['walk_forward', 'walk_backward'],
      strafe: ['strafe_left', 'strafe_right'],
      attack: ['attack_quick', 'attack_heavy', 'attack_thrust'],
      backstep: ['backstep'],
      knockback: ['clash_knockback', 'block_knockback'],
    },
    clipSpeedFactor: { walk: 2, strafe: 2, attack: 2, backstep: 3, knockback: 2 },
    clipSpeedOverrides: {
      attack_quick: 0.85,
      attack_heavy: 0.85,
      backstep: 0.8333333333333334,
      block_parry: 7.5,
      clash_knockback: 2.734375,
      block_knockback: 2.734375,
    },
    bakeWeapon: true,
    aiRanges: { engage: 2.8, close: 1.8 },
    attackStrength: 1.1,
    defenseStoutness: 1.05,
    sidestepDistance: 1.2,
    sidestepRecoveryFrames: 5,
    bodySeparation: 1.6,
    weaponClashRadius: DEFAULT_WEAPON_TUNING[WeaponType.KATANA].clashRadius,
    weaponHitRadius: DEFAULT_WEAPON_TUNING[WeaponType.KATANA].hitRadius,
  },
};

export const DEFAULT_CHAR = 'spearman';
