const COMMON_DEFAULTS = Object.freeze({
  reactionFrames: 15,
  decisionNoise: 0.2,
  aggression: 0.5,
  parryRate: 0.15,
  dodgeRate: 0.2,
  counterRate: 0.5,
  punishRate: 0.4,
  heavyMixup: 0.3,
  spacingAwareness: 0.5,
  quickBias: 0,
  heavyBias: 0,
  thrustBias: 0,
  blockBias: 0,
  parryBias: 0,
  sidestepBias: 0,
  backstepBias: 0,
  moveForwardBias: 0,
  moveBackBias: 0,
  idleBias: 0,
});

export const AI_PROFILE_LIBRARY = {
  baseline: {
    ...COMMON_DEFAULTS,
  },
  aggressor: {
    ...COMMON_DEFAULTS,
    reactionFrames: 10,
    decisionNoise: 0.1,
    aggression: 0.9,
    parryRate: 0.08,
    dodgeRate: 0.12,
    counterRate: 0.25,
    punishRate: 0.35,
    heavyMixup: 0.45,
    spacingAwareness: 0.15,
    quickBias: 0.15,
    heavyBias: 0.12,
    moveForwardBias: 0.18,
    sidestepBias: -0.08,
    moveBackBias: -0.1,
  },
  turtler: {
    ...COMMON_DEFAULTS,
    reactionFrames: 12,
    decisionNoise: 0.1,
    aggression: 0.28,
    parryRate: 0.1,
    dodgeRate: 0.15,
    counterRate: 0.25,
    punishRate: 0.35,
    heavyMixup: 0.05,
    spacingAwareness: 0.75,
    blockBias: 0.22,
    moveBackBias: 0.1,
    sidestepBias: -0.02,
    moveForwardBias: -0.1,
    quickBias: 0.04,
  },
  duelist: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.08,
    aggression: 0.45,
    parryRate: 0.45,
    dodgeRate: 0.18,
    counterRate: 0.8,
    punishRate: 0.7,
    heavyMixup: 0.2,
    spacingAwareness: 0.6,
    parryBias: 0.2,
    thrustBias: 0.1,
    blockBias: -0.08,
  },
  evasive: {
    ...COMMON_DEFAULTS,
    reactionFrames: 8,
    decisionNoise: 0.12,
    aggression: 0.45,
    parryRate: 0.08,
    dodgeRate: 0.45,
    counterRate: 0.35,
    punishRate: 0.65,
    heavyMixup: 0.1,
    spacingAwareness: 0.8,
    sidestepBias: 0.08,
    backstepBias: 0.02,
    moveBackBias: 0.04,
    moveForwardBias: 0.06,
    quickBias: 0.08,
    blockBias: -0.05,
    idleBias: -0.08,
  },
  punisher: {
    ...COMMON_DEFAULTS,
    reactionFrames: 7,
    decisionNoise: 0.06,
    aggression: 0.4,
    parryRate: 0.18,
    dodgeRate: 0.25,
    counterRate: 0.75,
    punishRate: 0.9,
    heavyMixup: 0.35,
    spacingAwareness: 0.85,
    heavyBias: 0.08,
    thrustBias: 0.12,
    moveForwardBias: -0.05,
    idleBias: -0.05,
  },
  heavy_bully: {
    ...COMMON_DEFAULTS,
    reactionFrames: 9,
    decisionNoise: 0.08,
    aggression: 0.78,
    parryRate: 0.06,
    dodgeRate: 0.12,
    counterRate: 0.22,
    punishRate: 0.45,
    heavyMixup: 0.9,
    spacingAwareness: 0.28,
    quickBias: -0.08,
    heavyBias: 0.55,
    thrustBias: -0.04,
    blockBias: -0.02,
    sidestepBias: -0.06,
    backstepBias: -0.05,
    moveForwardBias: 0.2,
    moveBackBias: -0.12,
    idleBias: -0.14,
  },
  lancer: {
    ...COMMON_DEFAULTS,
    reactionFrames: 7,
    decisionNoise: 0.06,
    aggression: 0.58,
    parryRate: 0.16,
    dodgeRate: 0.18,
    counterRate: 0.62,
    punishRate: 0.82,
    heavyMixup: 0.08,
    spacingAwareness: 0.72,
    quickBias: 0.04,
    heavyBias: -0.08,
    thrustBias: 0.42,
    blockBias: 0.08,
    parryBias: 0.06,
    sidestepBias: -0.06,
    backstepBias: -0.02,
    moveForwardBias: 0.14,
    moveBackBias: -0.02,
    idleBias: -0.08,
  },
  scrapper: {
    ...COMMON_DEFAULTS,
    reactionFrames: 9,
    decisionNoise: 0.09,
    aggression: 0.82,
    parryRate: 0.1,
    dodgeRate: 0.18,
    counterRate: 0.38,
    punishRate: 0.5,
    heavyMixup: 0.18,
    spacingAwareness: 0.22,
    quickBias: 0.28,
    heavyBias: -0.06,
    thrustBias: -0.02,
    blockBias: -0.04,
    parryBias: -0.02,
    sidestepBias: 0.02,
    backstepBias: -0.04,
    moveForwardBias: 0.18,
    moveBackBias: -0.12,
    idleBias: -0.16,
  },
  sentinel: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.06,
    aggression: 0.38,
    parryRate: 0.34,
    dodgeRate: 0.12,
    counterRate: 0.78,
    punishRate: 0.82,
    heavyMixup: 0.12,
    spacingAwareness: 0.72,
    quickBias: 0.02,
    heavyBias: 0.02,
    thrustBias: 0.14,
    blockBias: 0.3,
    parryBias: 0.24,
    sidestepBias: -0.06,
    backstepBias: -0.02,
    moveForwardBias: 0.02,
    moveBackBias: 0.04,
    idleBias: -0.04,
  },
  counter_guard: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.04,
    aggression: 0.3,
    parryRate: 0.42,
    dodgeRate: 0.08,
    counterRate: 0.92,
    punishRate: 0.88,
    heavyMixup: 0.14,
    spacingAwareness: 0.74,
    quickBias: 0.02,
    heavyBias: 0,
    thrustBias: 0.16,
    blockBias: 0.34,
    parryBias: 0.28,
    sidestepBias: -0.08,
    backstepBias: -0.03,
    moveForwardBias: -0.02,
    moveBackBias: 0.06,
    idleBias: -0.02,
  },
  skirmisher: {
    ...COMMON_DEFAULTS,
    reactionFrames: 8,
    decisionNoise: 0.07,
    aggression: 0.6,
    parryRate: 0.14,
    dodgeRate: 0.24,
    counterRate: 0.58,
    punishRate: 0.76,
    heavyMixup: 0.18,
    spacingAwareness: 0.58,
    quickBias: 0.1,
    heavyBias: -0.02,
    thrustBias: 0.22,
    blockBias: 0.02,
    parryBias: 0.02,
    sidestepBias: 0.01,
    backstepBias: -0.02,
    moveForwardBias: 0.12,
    moveBackBias: -0.02,
    idleBias: -0.08,
  },
  huscarl_raider: {
    ...COMMON_DEFAULTS,
    reactionFrames: 7,
    decisionNoise: 0.07,
    aggression: 0.86,
    parryRate: 0.16,
    dodgeRate: 0.14,
    counterRate: 0.5,
    punishRate: 0.7,
    heavyMixup: 0.22,
    spacingAwareness: 0.16,
    quickBias: 0.32,
    heavyBias: 0.04,
    thrustBias: 0.18,
    blockBias: -0.04,
    parryBias: 0.02,
    sidestepBias: -0.04,
    backstepBias: -0.14,
    moveForwardBias: 0.32,
    moveBackBias: -0.22,
    idleBias: -0.2,
  },
  spearman_evasive: {
    ...COMMON_DEFAULTS,
    reactionFrames: 8,
    decisionNoise: 0.1,
    aggression: 0.38,
    parryRate: 0.08,
    dodgeRate: 0.24,
    counterRate: 0.44,
    punishRate: 0.78,
    heavyMixup: 0.2,
    spacingAwareness: 0.96,
    quickBias: 0.02,
    heavyBias: 0.12,
    thrustBias: 0.32,
    blockBias: -0.04,
    sidestepBias: -0.02,
    backstepBias: 0.1,
    moveForwardBias: 0,
    moveBackBias: 0.16,
    idleBias: -0.08,
  },
  spearman_heavy_bully: {
    ...COMMON_DEFAULTS,
    reactionFrames: 9,
    decisionNoise: 0.08,
    aggression: 0.72,
    parryRate: 0.05,
    dodgeRate: 0.1,
    counterRate: 0.22,
    punishRate: 0.46,
    heavyMixup: 0.95,
    spacingAwareness: 0.34,
    quickBias: -0.12,
    heavyBias: 0.62,
    thrustBias: 0.08,
    blockBias: -0.04,
    sidestepBias: -0.1,
    backstepBias: -0.04,
    moveForwardBias: 0.24,
    moveBackBias: -0.1,
    idleBias: -0.14,
  },
  spearman_aggressor: {
    ...COMMON_DEFAULTS,
    reactionFrames: 9,
    decisionNoise: 0.08,
    aggression: 0.76,
    parryRate: 0.06,
    dodgeRate: 0.08,
    counterRate: 0.24,
    punishRate: 0.5,
    heavyMixup: 0.36,
    spacingAwareness: 0.34,
    quickBias: -0.06,
    heavyBias: 0.1,
    thrustBias: 0.34,
    blockBias: -0.04,
    sidestepBias: -0.12,
    backstepBias: -0.06,
    moveForwardBias: 0.2,
    moveBackBias: -0.08,
    idleBias: -0.14,
  },
  spearman_hard_line: {
    ...COMMON_DEFAULTS,
    reactionFrames: 8,
    decisionNoise: 0.06,
    aggression: 0.72,
    parryRate: 0.1,
    dodgeRate: 0.12,
    counterRate: 0.42,
    punishRate: 0.6,
    heavyMixup: 0.82,
    spacingAwareness: 0.42,
    quickBias: -0.04,
    heavyBias: 0.46,
    thrustBias: -0.12,
    blockBias: 0.04,
    parryBias: 0.04,
    sidestepBias: -0.1,
    backstepBias: -0.04,
    moveForwardBias: 0.22,
    moveBackBias: -0.08,
    idleBias: -0.12,
  },
  ronin_evasive: {
    ...COMMON_DEFAULTS,
    reactionFrames: 7,
    decisionNoise: 0.1,
    aggression: 0.48,
    parryRate: 0.1,
    dodgeRate: 0.38,
    counterRate: 0.4,
    punishRate: 0.72,
    heavyMixup: 0.1,
    spacingAwareness: 0.78,
    quickBias: 0.16,
    heavyBias: -0.08,
    thrustBias: 0.16,
    blockBias: -0.04,
    sidestepBias: 0.1,
    backstepBias: 0.02,
    moveForwardBias: 0.08,
    moveBackBias: 0.02,
    idleBias: -0.1,
  },
  ronin_aggressor: {
    ...COMMON_DEFAULTS,
    reactionFrames: 8,
    decisionNoise: 0.07,
    aggression: 0.72,
    parryRate: 0.1,
    dodgeRate: 0.18,
    counterRate: 0.4,
    punishRate: 0.56,
    heavyMixup: 0.22,
    spacingAwareness: 0.4,
    quickBias: 0.22,
    heavyBias: 0,
    thrustBias: 0.18,
    blockBias: -0.04,
    sidestepBias: 0.02,
    backstepBias: -0.02,
    moveForwardBias: 0.14,
    moveBackBias: -0.04,
    idleBias: -0.1,
  },
  ronin_lancer: {
    ...COMMON_DEFAULTS,
    reactionFrames: 7,
    decisionNoise: 0.06,
    aggression: 0.5,
    parryRate: 0.16,
    dodgeRate: 0.16,
    counterRate: 0.7,
    punishRate: 0.88,
    heavyMixup: 0.06,
    spacingAwareness: 0.84,
    quickBias: 0.18,
    heavyBias: -0.12,
    thrustBias: 0.3,
    blockBias: 0.08,
    parryBias: 0.06,
    sidestepBias: -0.06,
    backstepBias: 0.02,
    moveForwardBias: 0.04,
    moveBackBias: 0.02,
    idleBias: -0.08,
  },
  ronin_duelist: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.06,
    aggression: 0.44,
    parryRate: 0.28,
    dodgeRate: 0.18,
    counterRate: 0.76,
    punishRate: 0.78,
    heavyMixup: 0.04,
    spacingAwareness: 0.7,
    quickBias: 0.12,
    heavyBias: -0.08,
    thrustBias: 0.16,
    blockBias: 0.02,
    parryBias: 0.14,
    sidestepBias: 0.04,
    backstepBias: 0,
    moveForwardBias: 0.04,
    moveBackBias: 0.02,
    idleBias: -0.08,
  },
  ronin_hard_duelist: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.08,
    aggression: 0.4,
    parryRate: 0.38,
    dodgeRate: 0.14,
    counterRate: 0.78,
    punishRate: 0.74,
    heavyMixup: 0.32,
    spacingAwareness: 0.58,
    quickBias: -0.04,
    heavyBias: 0.16,
    thrustBias: 0.08,
    blockBias: 0.02,
    parryBias: 0.18,
    sidestepBias: -0.04,
    backstepBias: -0.02,
    moveForwardBias: 0,
    moveBackBias: 0,
    idleBias: 0,
  },
  knight_duelist: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.08,
    aggression: 0.4,
    parryRate: 0.38,
    dodgeRate: 0.14,
    counterRate: 0.78,
    punishRate: 0.74,
    heavyMixup: 0.32,
    spacingAwareness: 0.58,
    quickBias: -0.04,
    heavyBias: 0.16,
    thrustBias: 0.08,
    blockBias: 0.02,
    parryBias: 0.18,
    sidestepBias: -0.04,
    backstepBias: -0.02,
  },
  knight_bulwark: {
    ...COMMON_DEFAULTS,
    reactionFrames: 7,
    decisionNoise: 0.06,
    aggression: 0.5,
    parryRate: 0.24,
    dodgeRate: 0.08,
    counterRate: 0.74,
    punishRate: 0.82,
    heavyMixup: 0.4,
    spacingAwareness: 0.64,
    quickBias: -0.04,
    heavyBias: 0.26,
    thrustBias: 0.1,
    blockBias: 0.28,
    parryBias: 0.08,
    sidestepBias: -0.1,
    backstepBias: 0.02,
    moveBackBias: 0.02,
    moveForwardBias: 0.08,
    idleBias: -0.04,
  },
  knight_sentinel: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.05,
    aggression: 0.34,
    parryRate: 0.28,
    dodgeRate: 0.1,
    counterRate: 0.76,
    punishRate: 0.8,
    heavyMixup: 0.18,
    spacingAwareness: 0.72,
    quickBias: -0.02,
    heavyBias: 0.12,
    thrustBias: 0.12,
    blockBias: 0.3,
    parryBias: 0.2,
    sidestepBias: -0.08,
    backstepBias: 0.02,
    moveForwardBias: -0.02,
    moveBackBias: 0.06,
    idleBias: -0.02,
  },
  knight_hard_guard: {
    ...COMMON_DEFAULTS,
    reactionFrames: 6,
    decisionNoise: 0.04,
    aggression: 0.3,
    parryRate: 0.42,
    dodgeRate: 0.08,
    counterRate: 0.9,
    punishRate: 0.88,
    heavyMixup: 0.14,
    spacingAwareness: 0.74,
    quickBias: 0.02,
    heavyBias: 0,
    thrustBias: 0.16,
    blockBias: 0.34,
    parryBias: 0.28,
    sidestepBias: -0.08,
    backstepBias: -0.03,
    moveForwardBias: -0.02,
    moveBackBias: 0.06,
    idleBias: -0.02,
  },
};

export const AI_CLASS_PROFILE_SETS = Object.freeze({
  spearman: ['spearman_evasive', 'spearman_heavy_bully', 'spearman_aggressor', 'spearman_hard_line'],
  ronin: ['ronin_evasive', 'ronin_lancer', 'ronin_duelist', 'ronin_hard_duelist'],
  knight: ['knight_duelist', 'knight_bulwark', 'knight_sentinel', 'knight_hard_guard'],
  huscarl: ['huscarl_raider', 'scrapper', 'skirmisher', 'aggressor'],
});

export const AI_DIFFICULTY_ALIASES = Object.freeze({
  easy: 'turtler',
  medium: 'punisher',
  hard: 'evasive',
});

export const AI_PRESETS = {
  easy: AI_PROFILE_LIBRARY[AI_DIFFICULTY_ALIASES.easy],
  medium: AI_PROFILE_LIBRARY[AI_DIFFICULTY_ALIASES.medium],
  hard: AI_PROFILE_LIBRARY[AI_DIFFICULTY_ALIASES.hard],
};

export function resolveAIPersonality(profile) {
  if (typeof profile === 'string') {
    const aliasTarget = AI_DIFFICULTY_ALIASES[profile];
    if (aliasTarget) {
      return {
        name: profile,
        personality: { ...AI_PROFILE_LIBRARY[aliasTarget] },
        baseProfile: aliasTarget,
      };
    }

    const personality = AI_PROFILE_LIBRARY[profile] || AI_PROFILE_LIBRARY.baseline;
    return {
      name: profile in AI_PROFILE_LIBRARY ? profile : 'baseline',
      personality: { ...personality },
      baseProfile: profile in AI_PROFILE_LIBRARY ? profile : 'baseline',
    };
  }
  return {
    name: profile?.name || 'custom',
    personality: { ...COMMON_DEFAULTS, ...(profile || {}) },
    baseProfile: 'custom',
  };
}
